// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBcw2RruVPM0e4SBkakRNkURtKtROSklV0",
      authDomain: "chatmeflutterapp.firebaseapp.com",
      projectId: "chatmeflutterapp",
      storageBucket: "chatmeflutterapp.appspot.com",
      messagingSenderId: "1078460833504",
      appId: "1:1078460833504:web:d8fb7f6b23178dda737a85",
      measurementId: "G-13YJMMBGHK"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72SjCBNUlcYYRcC8tyEEMfHRPkFTc6W0',
    appId: '1:1078460833504:android:2f1bd4429c3eb8cc737a85',
    messagingSenderId: '1078460833504',
    projectId: 'chatmeflutterapp',
    storageBucket: 'chatmeflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaOu1GruVuBM7sibgdlMH_48PDXv2gc-I',
    appId: '1:1078460833504:ios:90c670b382715eeb737a85',
    messagingSenderId: '1078460833504',
    projectId: 'chatmeflutterapp',
    storageBucket: 'chatmeflutterapp.appspot.com',
    androidClientId: '1078460833504-6ltdn1410f7gj6jtfenamsi2opmg6hqv.apps.googleusercontent.com',
    iosClientId: '1078460833504-o6lctkf0erb4j2hkug9romj1cqbqhu8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatme',
  );
}
